import Layout from "@/components/Layout";
import "@/styles/globals.css";
import Head from "next/head";

export default function App({ Component, pageProps, router }) {
  if (!router.pathname.startsWith("/Landlord")) {
    return (
      <>
        <Head>
          <title>UPD Alternative Housing Portal</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
          <Layout>
            <Component {...pageProps} />
          </Layout>
      </>
    );
  }
  return <Component {...pageProps} />;
}
